// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestaurantManagement.API.Data;

#nullable disable

namespace RestaurantManagement.API.Migrations
{
    [DbContext(typeof(RestaurantDbContext))]
    partial class RestaurantDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("VaiTro", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("VaiTroClaim", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("TaiKhoanClaim", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("DangNhapNgoai", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("TaiKhoanVaiTro", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("TokenTaiKhoan", (string)null);
                });

            modelBuilder.Entity("RestaurantManagement.API.Models.BanAn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("KhuVucId")
                        .HasColumnType("int");

                    b.Property<string>("MaBan")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("SoChoNgoi")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("KhuVucId");

                    b.HasIndex("MaBan")
                        .IsUnique();

                    b.ToTable("BanAn", null, t =>
                        {
                            t.HasCheckConstraint("CK_BanAn_SoCho", "[SoChoNgoi]>0");

                            t.HasCheckConstraint("CK_BanAn_TrangThai_Enum", "[TrangThai] IN ('SanSang','DangPhucVu','CanDon','NgungSuDung')");
                        });
                });

            modelBuilder.Entity("RestaurantManagement.API.Models.ChiTietCombo", b =>
                {
                    b.Property<int>("ComboId")
                        .HasColumnType("int");

                    b.Property<int>("MonAnId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("ComboId", "MonAnId");

                    b.HasIndex("MonAnId");

                    b.ToTable("ChiTietCombo", null, t =>
                        {
                            t.HasCheckConstraint("CK_ChiTietCombo_ThanhPhan", "[ComboId]<>[MonAnId] AND [SoLuong]>0");
                        });
                });

            modelBuilder.Entity("RestaurantManagement.API.Models.ChiTietDatBan", b =>
                {
                    b.Property<int>("DatBanId")
                        .HasColumnType("int");

                    b.Property<int>("BanAnId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("DatBanId", "BanAnId");

                    b.HasIndex("BanAnId");

                    b.ToTable("ChiTietDatBan", (string)null);
                });

            modelBuilder.Entity("RestaurantManagement.API.Models.ChiTietHoaDon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChiTietComboSnapshot")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<decimal>("DonGia")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("HoaDonId")
                        .HasColumnType("int");

                    b.Property<int>("MonAnId")
                        .HasColumnType("int");

                    b.Property<int?>("MonAnSizeId")
                        .HasColumnType("int");

                    b.Property<int?>("MonDatTruocId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("TenMonLucBan")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("YeuCauCheBien")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("HoaDonId");

                    b.HasIndex("MonAnId");

                    b.HasIndex("MonAnSizeId");

                    b.HasIndex("MonDatTruocId")
                        .IsUnique()
                        .HasFilter("[MonDatTruocId] IS NOT NULL");

                    b.ToTable("ChiTietHoaDon", null, t =>
                        {
                            t.HasCheckConstraint("CK_ChiTietHoaDon_LuongGia", "[SoLuong]>0 AND [DonGia]>=0");

                            t.HasCheckConstraint("CK_ChiTietHoaDon_TrangThai_Enum", "[TrangThai] IN ('ChoCheBien','DangCheBien','SanSang','DaPhucVu','DaHuy')");
                        });
                });

            modelBuilder.Entity("RestaurantManagement.API.Models.ChiTietPhieuNhap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DonGia")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly?>("HanSuDung")
                        .HasColumnType("date");

                    b.Property<string>("MaLo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("NguyenLieuId")
                        .HasColumnType("int");

                    b.Property<int>("PhieuNhapId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<decimal>("SoLuong")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.HasKey("Id");

                    b.HasIndex("NguyenLieuId");

                    b.HasIndex("PhieuNhapId");

                    b.ToTable("ChiTietPhieuNhap", null, t =>
                        {
                            t.HasCheckConstraint("CK_ChiTietPhieuNhap_LuongGia", "[SoLuong]>0 AND [DonGia]>=0");
                        });
                });

            modelBuilder.Entity("RestaurantManagement.API.Models.ChiTietPhieuXuat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ChiTietPhieuNhapId")
                        .HasColumnType("int");

                    b.Property<int>("NguyenLieuId")
                        .HasColumnType("int");

                    b.Property<int>("PhieuXuatId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<decimal>("SoLuong")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.HasKey("Id");

                    b.HasIndex("ChiTietPhieuNhapId");

                    b.HasIndex("NguyenLieuId");

                    b.HasIndex("PhieuXuatId");

                    b.ToTable("ChiTietPhieuXuat", null, t =>
                        {
                            t.HasCheckConstraint("CK_ChiTietPhieuXuat_SoLuong", "[SoLuong]>0");
                        });
                });

            modelBuilder.Entity("RestaurantManagement.API.Models.DanhGia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ChiTietHoaDonId")
                        .HasColumnType("int");

                    b.Property<int>("Diem")
                        .HasColumnType("int");

                    b.Property<int>("HoaDonId")
                        .HasColumnType("int");

                    b.Property<int?>("KhachHangId")
                        .HasColumnType("int");

                    b.Property<string>("NoiDung")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset>("ThoiDiem")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("KhachHangId");

                    b.HasIndex("ChiTietHoaDonId", "HoaDonId");

                    b.HasIndex("HoaDonId", "ChiTietHoaDonId")
                        .IsUnique();

                    b.ToTable("DanhGia", null, t =>
                        {
                            t.HasCheckConstraint("CK_DanhGia_Diem", "[Diem] BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("RestaurantManagement.API.Models.DanhMuc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("DangSuDung")
                        .HasColumnType("bit");

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("TenDanhMuc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("TenDanhMuc")
                        .IsUnique();

                    b.ToTable("DanhMuc", (string)null);
                });

            modelBuilder.Entity("RestaurantManagement.API.Models.DatBan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DieuKienCocDaThoaThuan")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTimeOffset>("GioDen")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("GioKetThucDuKien")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("HoTenLienHe")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int?>("KhachHangId")
                        .HasColumnType("int");

                    b.Property<bool>("LaKhachTrucTiep")
                        .HasColumnType("bit");

                    b.Property<string>("LyDoHuy")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MaDatBan")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("NhanVienHuyId")
                        .HasColumnType("int");

                    b.Property<int?>("NhanVienTiepNhanId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SoDienThoaiLienHe")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SoNguoiLon")
                        .HasColumnType("int");

                    b.Property<int>("SoTreEm")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("ThoiDiemCoc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ThoiDiemHuy")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ThoiDiemNhanBan")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ThoiDiemTao")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("TienCocDaNop")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TienCocYeuCau")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("TrangThaiCoc")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("YeuCau")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("YeuCauTrangTri")
                        .HasColumnType("bit");

                    b.Property<bool>("YeuCauVip")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("KhachHangId");

                    b.HasIndex("MaDatBan")
                        .IsUnique();

                    b.HasIndex("NhanVienHuyId");

                    b.HasIndex("NhanVienTiepNhanId");

                    b.HasIndex("TrangThai", "GioDen", "GioKetThucDuKien");

                    b.ToTable("DatBan", null, t =>
                        {
                            t.HasCheckConstraint("CK_DatBan_Coc", "[TienCocYeuCau]>=0 AND [TienCocDaNop]>=0");

                            t.HasCheckConstraint("CK_DatBan_LienHe", "[LaKhachTrucTiep]=1 OR ([SoDienThoaiLienHe] IS NOT NULL AND LEN([SoDienThoaiLienHe])>0)");

                            t.HasCheckConstraint("CK_DatBan_NhanHuy", "([TrangThai]<>'DaNhanBan' OR [ThoiDiemNhanBan] IS NOT NULL) AND ([TrangThai]<>'DaHuy' OR [ThoiDiemHuy] IS NOT NULL)");

                            t.HasCheckConstraint("CK_DatBan_SoKhach", "[SoNguoiLon]>=0 AND [SoTreEm]>=0 AND [SoNguoiLon]+[SoTreEm]>0");

                            t.HasCheckConstraint("CK_DatBan_ThoiGian", "[GioKetThucDuKien]>[GioDen]");

                            t.HasCheckConstraint("CK_DatBan_TrangThaiCoc_Enum", "[TrangThaiCoc] IN ('ChuaCoc','DaCoc','DaHoan','DaDoiTru')");

                            t.HasCheckConstraint("CK_DatBan_TrangThai_Enum", "[TrangThai] IN ('ChoXacNhan','ChoCoc','DaXacNhan','DaNhanBan','DaHuy','KhongDen')");
                        });
                });

            modelBuilder.Entity("RestaurantManagement.API.Models.DinhMucMon", b =>
                {
                    b.Property<int>("MonAnId")
                        .HasColumnType("int");

                    b.Property<int>("NguyenLieuId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<decimal>("SoLuong")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.HasKey("MonAnId", "NguyenLieuId");

                    b.HasIndex("NguyenLieuId");

                    b.ToTable("DinhMucMon", null, t =>
                        {
                            t.HasCheckConstraint("CK_DinhMucMon_SoLuong", "[SoLuong]>0");
                        });
                });

            modelBuilder.Entity("RestaurantManagement.API.Models.HoaDon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DatBanId")
                        .HasColumnType("int");

                    b.Property<int?>("KhachHangId")
                        .HasColumnType("int");

                    b.Property<string>("MaHoaDon")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("NhanVienId")
                        .HasColumnType("int");

                    b.Property<string>("PhuongThucThanhToan")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset>("ThoiDiemLap")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ThoiDiemThanhToan")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("TienCocDaTru")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TienGiam")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TongThanhToan")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasComputedColumnSql("[TongTienHang]-[TienGiam]-[TienCocDaTru]", true);

                    b.Property<decimal>("TongTienHang")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int?>("VoucherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DatBanId");

                    b.HasIndex("KhachHangId");

                    b.HasIndex("MaHoaDon")
                        .IsUnique();

                    b.HasIndex("NhanVienId");

                    b.HasIndex("VoucherId");

                    b.ToTable("HoaDon", null, t =>
                        {
                            t.HasCheckConstraint("CK_HoaDon_PhuongThucThanhToan_Enum", "[PhuongThucThanhToan] IN ('TienMat','ChuyenKhoan','The','ViDienTu')");

                            t.HasCheckConstraint("CK_HoaDon_SoTien", "[TongTienHang]>=0 AND [TienGiam]>=0 AND [TienGiam]<=[TongTienHang] AND [TienCocDaTru]>=0 AND [TienCocDaTru]<=[TongTienHang]-[TienGiam]");

                            t.HasCheckConstraint("CK_HoaDon_TrangThai_Enum", "[TrangThai] IN ('ChuaThanhToan','ThanhToanMotPhan','DaThanhToan','DaHuy')");
                        });
                });

            modelBuilder.Entity("RestaurantManagement.API.Models.KhachHang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("DangSuDung")
                        .HasColumnType("bit");

                    b.Property<bool>("DongYNhanUuDai")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTimeOffset>("NgayDangKy")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("TaiKhoanId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("ThoiDiemDongYNhanUuDai")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("SoDienThoai")
                        .IsUnique();

                    b.HasIndex("TaiKhoanId")
                        .IsUnique()
                        .HasFilter("[TaiKhoanId] IS NOT NULL");

                    b.ToTable("KhachHang", (string)null);
                });

            modelBuilder.Entity("RestaurantManagement.API.Models.KhuVuc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("DangSuDung")
                        .HasColumnType("bit");

                    b.Property<bool>("LaPhongVip")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("TenKhuVuc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("KhuVuc", (string)null);
                });

            modelBuilder.Entity("RestaurantManagement.API.Models.KhuyenMai", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("BatDau")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("CanVoucher")
                        .HasColumnType("bit");

                    b.Property<bool>("ChoPhepKetHop")
                        .HasColumnType("bit");

                    b.Property<bool>("DangSuDung")
                        .HasColumnType("bit");

                    b.Property<decimal>("GiaTri")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GiaTriToiThieu")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset>("KetThuc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("KieuGiam")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<decimal?>("MucGiamToiDa")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PhamVi")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("TenChuongTrinh")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("ThuTuApDung")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("KhuyenMai", null, t =>
                        {
                            t.HasCheckConstraint("CK_KhuyenMai_DieuKien", "[KetThuc]>[BatDau] AND [GiaTri]>0 AND ([KieuGiam]<>'PhanTram' OR [GiaTri]<=100) AND [GiaTriToiThieu]>=0 AND ([MucGiamToiDa] IS NULL OR [MucGiamToiDa]>0) AND [ThuTuApDung]>=0");

                            t.HasCheckConstraint("CK_KhuyenMai_KieuGiam_Enum", "[KieuGiam] IN ('PhanTram','SoTien')");

                            t.HasCheckConstraint("CK_KhuyenMai_PhamVi_Enum", "[PhamVi] IN ('MonAn','HoaDon')");
                        });
                });

            modelBuilder.Entity("RestaurantManagement.API.Models.KhuyenMaiMon", b =>
                {
                    b.Property<int>("KhuyenMaiId")
                        .HasColumnType("int");

                    b.Property<int>("MonAnId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("KhuyenMaiId", "MonAnId");

                    b.HasIndex("MonAnId");

                    b.ToTable("KhuyenMaiMon", (string)null);
                });

            modelBuilder.Entity("RestaurantManagement.API.Models.MonAn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DanhMucId")
                        .HasColumnType("int");

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("LaMonMoi")
                        .HasColumnType("bit");

                    b.Property<bool>("LaMonNoiBat")
                        .HasColumnType("bit");

                    b.Property<string>("Loai")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("TenMon")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("DanhMucId");

                    b.ToTable("MonAn", null, t =>
                        {
                            t.HasCheckConstraint("CK_MonAn_Loai_Enum", "[Loai] IN ('MonLe','ThucUong','Set')");

                            t.HasCheckConstraint("CK_MonAn_TrangThai_Enum", "[TrangThai] IN ('DangPhucVu','TamHet','NgungKinhDoanh')");
                        });
                });

            modelBuilder.Entity("RestaurantManagement.API.Models.MonAnSize", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("DangSuDung")
                        .HasColumnType("bit");

                    b.Property<decimal>("GiaBan")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MonAnId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("TenSize")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("MonAnId", "TenSize")
                        .IsUnique();

                    b.ToTable("MonAnSize", null, t =>
                        {
                            t.HasCheckConstraint("CK_MonAnSize_Gia", "[GiaBan]>=0");
                        });
                });

            modelBuilder.Entity("RestaurantManagement.API.Models.MonDatTruoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChiTietComboSnapshot")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("DatBanId")
                        .HasColumnType("int");

                    b.Property<decimal>("DonGiaThoaThuan")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MonAnId")
                        .HasColumnType("int");

                    b.Property<int?>("MonAnSizeId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("TenMonLucDat")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("YeuCauCheBien")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("DatBanId");

                    b.HasIndex("MonAnId");

                    b.HasIndex("MonAnSizeId");

                    b.ToTable("MonDatTruoc", null, t =>
                        {
                            t.HasCheckConstraint("CK_MonDatTruoc_LuongGia", "[SoLuong]>0 AND [DonGiaThoaThuan]>=0");
                        });
                });

            modelBuilder.Entity("RestaurantManagement.API.Models.NguyenLieu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("DangSuDung")
                        .HasColumnType("bit");

                    b.Property<string>("DonViTinh")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("NguongCanhBao")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("TenNguyenLieu")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("TenNguyenLieu")
                        .IsUnique();

                    b.ToTable("NguyenLieu", null, t =>
                        {
                            t.HasCheckConstraint("CK_NguyenLieu_Nguong", "[NguongCanhBao]>=0");
                        });
                });

            modelBuilder.Entity("RestaurantManagement.API.Models.NhaCungCap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("DangSuDung")
                        .HasColumnType("bit");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("MaSoThue")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TenNhaCungCap")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("NhaCungCap", (string)null);
                });

            modelBuilder.Entity("RestaurantManagement.API.Models.NhanVien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChucVu")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<bool>("DangLamViec")
                        .HasColumnType("bit");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("MaNhanVien")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateOnly>("NgayVaoLam")
                        .HasColumnType("date");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("TaiKhoanId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaNhanVien")
                        .IsUnique();

                    b.HasIndex("TaiKhoanId")
                        .IsUnique()
                        .HasFilter("[TaiKhoanId] IS NOT NULL");

                    b.ToTable("NhanVien", (string)null);
                });

            modelBuilder.Entity("RestaurantManagement.API.Models.PhieuNhap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LyDo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("MaPhieu")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("NhaCungCapId")
                        .HasColumnType("int");

                    b.Property<int>("NhanVienId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset>("ThoiDiem")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("MaPhieu")
                        .IsUnique();

                    b.HasIndex("NhaCungCapId");

                    b.HasIndex("NhanVienId");

                    b.ToTable("PhieuNhap", null, t =>
                        {
                            t.HasCheckConstraint("CK_PhieuNhap_LyDo_Enum", "[LyDo] IN ('MuaHang','TonDauKy','DieuChinhTang')");

                            t.HasCheckConstraint("CK_PhieuNhap_NhaCungCap", "[LyDo]<>'MuaHang' OR [NhaCungCapId] IS NOT NULL");

                            t.HasCheckConstraint("CK_PhieuNhap_TrangThai_Enum", "[TrangThai] IN ('Nhap','DaGhiSo','DaHuy')");
                        });
                });

            modelBuilder.Entity("RestaurantManagement.API.Models.PhieuXuat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("HoaDonId")
                        .HasColumnType("int");

                    b.Property<string>("LyDo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("MaPhieu")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("NhanVienId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset>("ThoiDiem")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("HoaDonId");

                    b.HasIndex("MaPhieu")
                        .IsUnique();

                    b.HasIndex("NhanVienId");

                    b.ToTable("PhieuXuat", null, t =>
                        {
                            t.HasCheckConstraint("CK_PhieuXuat_LyDo_Enum", "[LyDo] IN ('CheBien','ThanhLy','HuyHong','TraNhaCungCap','DieuChinhGiam')");

                            t.HasCheckConstraint("CK_PhieuXuat_TrangThai_Enum", "[TrangThai] IN ('Nhap','DaGhiSo','DaHuy')");
                        });
                });

            modelBuilder.Entity("RestaurantManagement.API.Models.TaiKhoan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("TaiKhoan", (string)null);
                });

            modelBuilder.Entity("RestaurantManagement.API.Models.Voucher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("DangSuDung")
                        .HasColumnType("bit");

                    b.Property<int>("GioiHanTongLuot")
                        .HasColumnType("int");

                    b.Property<int?>("KhachHangId")
                        .HasColumnType("int");

                    b.Property<int>("KhuyenMaiId")
                        .HasColumnType("int");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("KhachHangId");

                    b.HasIndex("KhuyenMaiId");

                    b.HasIndex("Ma")
                        .IsUnique();

                    b.ToTable("Voucher", null, t =>
                        {
                            t.HasCheckConstraint("CK_Voucher_Luot", "[GioiHanTongLuot]>0");
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("RestaurantManagement.API.Models.TaiKhoan", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("RestaurantManagement.API.Models.TaiKhoan", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RestaurantManagement.API.Models.TaiKhoan", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("RestaurantManagement.API.Models.TaiKhoan", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("RestaurantManagement.API.Models.BanAn", b =>
                {
                    b.HasOne("RestaurantManagement.API.Models.KhuVuc", "KhuVuc")
                        .WithMany()
                        .HasForeignKey("KhuVucId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KhuVuc");
                });

            modelBuilder.Entity("RestaurantManagement.API.Models.ChiTietCombo", b =>
                {
                    b.HasOne("RestaurantManagement.API.Models.MonAn", "Combo")
                        .WithMany("ThanhPhanCombo")
                        .HasForeignKey("ComboId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RestaurantManagement.API.Models.MonAn", "MonAn")
                        .WithMany()
                        .HasForeignKey("MonAnId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Combo");

                    b.Navigation("MonAn");
                });

            modelBuilder.Entity("RestaurantManagement.API.Models.ChiTietDatBan", b =>
                {
                    b.HasOne("RestaurantManagement.API.Models.BanAn", "BanAn")
                        .WithMany()
                        .HasForeignKey("BanAnId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RestaurantManagement.API.Models.DatBan", "DatBan")
                        .WithMany("Ban")
                        .HasForeignKey("DatBanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BanAn");

                    b.Navigation("DatBan");
                });

            modelBuilder.Entity("RestaurantManagement.API.Models.ChiTietHoaDon", b =>
                {
                    b.HasOne("RestaurantManagement.API.Models.HoaDon", "HoaDon")
                        .WithMany("ChiTiet")
                        .HasForeignKey("HoaDonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RestaurantManagement.API.Models.MonAn", "MonAn")
                        .WithMany()
                        .HasForeignKey("MonAnId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RestaurantManagement.API.Models.MonAnSize", "MonAnSize")
                        .WithMany()
                        .HasForeignKey("MonAnSizeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RestaurantManagement.API.Models.MonDatTruoc", "MonDatTruoc")
                        .WithOne()
                        .HasForeignKey("RestaurantManagement.API.Models.ChiTietHoaDon", "MonDatTruocId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("HoaDon");

                    b.Navigation("MonAn");

                    b.Navigation("MonAnSize");

                    b.Navigation("MonDatTruoc");
                });

            modelBuilder.Entity("RestaurantManagement.API.Models.ChiTietPhieuNhap", b =>
                {
                    b.HasOne("RestaurantManagement.API.Models.NguyenLieu", "NguyenLieu")
                        .WithMany()
                        .HasForeignKey("NguyenLieuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RestaurantManagement.API.Models.PhieuNhap", "PhieuNhap")
                        .WithMany("ChiTiet")
                        .HasForeignKey("PhieuNhapId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NguyenLieu");

                    b.Navigation("PhieuNhap");
                });

            modelBuilder.Entity("RestaurantManagement.API.Models.ChiTietPhieuXuat", b =>
                {
                    b.HasOne("RestaurantManagement.API.Models.ChiTietPhieuNhap", "LoNhap")
                        .WithMany()
                        .HasForeignKey("ChiTietPhieuNhapId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RestaurantManagement.API.Models.NguyenLieu", "NguyenLieu")
                        .WithMany()
                        .HasForeignKey("NguyenLieuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RestaurantManagement.API.Models.PhieuXuat", "PhieuXuat")
                        .WithMany("ChiTiet")
                        .HasForeignKey("PhieuXuatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LoNhap");

                    b.Navigation("NguyenLieu");

                    b.Navigation("PhieuXuat");
                });

            modelBuilder.Entity("RestaurantManagement.API.Models.DanhGia", b =>
                {
                    b.HasOne("RestaurantManagement.API.Models.HoaDon", "HoaDon")
                        .WithMany()
                        .HasForeignKey("HoaDonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RestaurantManagement.API.Models.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("KhachHangId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RestaurantManagement.API.Models.ChiTietHoaDon", "ChiTietHoaDon")
                        .WithMany()
                        .HasForeignKey("ChiTietHoaDonId", "HoaDonId")
                        .HasPrincipalKey("Id", "HoaDonId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ChiTietHoaDon");

                    b.Navigation("HoaDon");

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("RestaurantManagement.API.Models.DatBan", b =>
                {
                    b.HasOne("RestaurantManagement.API.Models.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("KhachHangId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RestaurantManagement.API.Models.NhanVien", "NhanVienHuy")
                        .WithMany()
                        .HasForeignKey("NhanVienHuyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RestaurantManagement.API.Models.NhanVien", "NhanVienTiepNhan")
                        .WithMany()
                        .HasForeignKey("NhanVienTiepNhanId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("KhachHang");

                    b.Navigation("NhanVienHuy");

                    b.Navigation("NhanVienTiepNhan");
                });

            modelBuilder.Entity("RestaurantManagement.API.Models.DinhMucMon", b =>
                {
                    b.HasOne("RestaurantManagement.API.Models.MonAn", "MonAn")
                        .WithMany()
                        .HasForeignKey("MonAnId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RestaurantManagement.API.Models.NguyenLieu", "NguyenLieu")
                        .WithMany()
                        .HasForeignKey("NguyenLieuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MonAn");

                    b.Navigation("NguyenLieu");
                });

            modelBuilder.Entity("RestaurantManagement.API.Models.HoaDon", b =>
                {
                    b.HasOne("RestaurantManagement.API.Models.DatBan", "DatBan")
                        .WithMany("HoaDon")
                        .HasForeignKey("DatBanId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RestaurantManagement.API.Models.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("KhachHangId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RestaurantManagement.API.Models.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("NhanVienId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RestaurantManagement.API.Models.Voucher", "Voucher")
                        .WithMany()
                        .HasForeignKey("VoucherId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DatBan");

                    b.Navigation("KhachHang");

                    b.Navigation("NhanVien");

                    b.Navigation("Voucher");
                });

            modelBuilder.Entity("RestaurantManagement.API.Models.KhachHang", b =>
                {
                    b.HasOne("RestaurantManagement.API.Models.TaiKhoan", "TaiKhoan")
                        .WithOne()
                        .HasForeignKey("RestaurantManagement.API.Models.KhachHang", "TaiKhoanId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("RestaurantManagement.API.Models.KhuyenMaiMon", b =>
                {
                    b.HasOne("RestaurantManagement.API.Models.KhuyenMai", "KhuyenMai")
                        .WithMany()
                        .HasForeignKey("KhuyenMaiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RestaurantManagement.API.Models.MonAn", "MonAn")
                        .WithMany()
                        .HasForeignKey("MonAnId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KhuyenMai");

                    b.Navigation("MonAn");
                });

            modelBuilder.Entity("RestaurantManagement.API.Models.MonAn", b =>
                {
                    b.HasOne("RestaurantManagement.API.Models.DanhMuc", "DanhMuc")
                        .WithMany("MonAn")
                        .HasForeignKey("DanhMucId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DanhMuc");
                });

            modelBuilder.Entity("RestaurantManagement.API.Models.MonAnSize", b =>
                {
                    b.HasOne("RestaurantManagement.API.Models.MonAn", "MonAn")
                        .WithMany("Sizes")
                        .HasForeignKey("MonAnId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MonAn");
                });

            modelBuilder.Entity("RestaurantManagement.API.Models.MonDatTruoc", b =>
                {
                    b.HasOne("RestaurantManagement.API.Models.DatBan", "DatBan")
                        .WithMany("MonDatTruoc")
                        .HasForeignKey("DatBanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RestaurantManagement.API.Models.MonAn", "MonAn")
                        .WithMany()
                        .HasForeignKey("MonAnId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RestaurantManagement.API.Models.MonAnSize", "MonAnSize")
                        .WithMany()
                        .HasForeignKey("MonAnSizeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DatBan");

                    b.Navigation("MonAn");

                    b.Navigation("MonAnSize");
                });

            modelBuilder.Entity("RestaurantManagement.API.Models.NhanVien", b =>
                {
                    b.HasOne("RestaurantManagement.API.Models.TaiKhoan", "TaiKhoan")
                        .WithOne()
                        .HasForeignKey("RestaurantManagement.API.Models.NhanVien", "TaiKhoanId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("RestaurantManagement.API.Models.PhieuNhap", b =>
                {
                    b.HasOne("RestaurantManagement.API.Models.NhaCungCap", "NhaCungCap")
                        .WithMany()
                        .HasForeignKey("NhaCungCapId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RestaurantManagement.API.Models.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("NhanVienId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NhaCungCap");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("RestaurantManagement.API.Models.PhieuXuat", b =>
                {
                    b.HasOne("RestaurantManagement.API.Models.HoaDon", "HoaDon")
                        .WithMany()
                        .HasForeignKey("HoaDonId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RestaurantManagement.API.Models.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("NhanVienId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HoaDon");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("RestaurantManagement.API.Models.Voucher", b =>
                {
                    b.HasOne("RestaurantManagement.API.Models.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("KhachHangId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RestaurantManagement.API.Models.KhuyenMai", "KhuyenMai")
                        .WithMany()
                        .HasForeignKey("KhuyenMaiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("KhuyenMai");
                });

            modelBuilder.Entity("RestaurantManagement.API.Models.DanhMuc", b =>
                {
                    b.Navigation("MonAn");
                });

            modelBuilder.Entity("RestaurantManagement.API.Models.DatBan", b =>
                {
                    b.Navigation("Ban");

                    b.Navigation("HoaDon");

                    b.Navigation("MonDatTruoc");
                });

            modelBuilder.Entity("RestaurantManagement.API.Models.HoaDon", b =>
                {
                    b.Navigation("ChiTiet");
                });

            modelBuilder.Entity("RestaurantManagement.API.Models.MonAn", b =>
                {
                    b.Navigation("Sizes");

                    b.Navigation("ThanhPhanCombo");
                });

            modelBuilder.Entity("RestaurantManagement.API.Models.PhieuNhap", b =>
                {
                    b.Navigation("ChiTiet");
                });

            modelBuilder.Entity("RestaurantManagement.API.Models.PhieuXuat", b =>
                {
                    b.Navigation("ChiTiet");
                });
#pragma warning restore 612, 618
        }
    }
}
